#!/usr/bin/env python3
"""
Mock Entegris IntelliGen NCS 

Very much generated by Claude
"""

import socket
import struct
import sys

# ---------------------------------------------------------------------------
# options
# ---------------------------------------------------------------------------

HOST = "127.0.0.1"
PORT = 4002

LITTLE_ENDIAN = True        # False to byte swap the header, probe should reject it
SIZE_INCLUDES_HEADER = True # False = size field counts the data only
LOGICAL_COM1 = 0            # logical serial number that COM1 maps to
IFACE_WIDTH = 4             # bytes GET_INTERFACES returns the count in, 2 or 4
CLOSE_AFTER_RESPONSE = True # False makes the client hit its own recv timeout

# ---------------------------------------------------------------------------

HDR_LEN = 18

SEND_PACKET, GET_INTERFACES, GET_NAME, GET_VERSION, QUERY_INTERFACE, \
    LOCK_INTERFACE, UNLOCK_INTERFACE = range(7)

CMD_NAMES = {
    SEND_PACKET: "SEND_PACKET",
    GET_INTERFACES: "GET_INTERFACES",
    GET_NAME: "GET_NAME",
    GET_VERSION: "GET_VERSION",
    QUERY_INTERFACE: "QUERY_INTERFACE",
    LOCK_INTERFACE: "LOCK_INTERFACE",
    UNLOCK_INTERFACE: "UNLOCK_INTERFACE",
}

NO_ERR                  = 0
ERR_UNKNOWN_COMMAND     = 1002
ERR_MALFORMED_PACKET    = 1003
ERR_UNKNOWN_SERIAL_PORT = 1004
ERR_SERIAL_READ_TIMEOUT = 1015

# what the fake box reports, shaped like the real About screen
VERSION = b"Entegris IntelliGen NCS sserver 4.14"
NAME = b"mock-ncs"
N_IFACE = 8
BAUDS = [57600, 57600, 38400, 38400, 57600, 57600, 57600, 19200]


def hexdump(label, data):
    print(f"{label} {len(data)} bytes")
    for off in range(0, len(data), 16):
        chunk = data[off:off + 16]
        hexpart = " ".join(f"{b:02x}" for b in chunk)
        txt = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        print(f"    {off:04x}  {hexpart:<47}  |{txt}|")


class Mock:
    def __init__(self):
        self.e = "<" if LITTLE_ENDIAN else ">"
        self.served = [0] * N_IFACE

    def response(self, rc, body=b""):
        size = HDR_LEN + len(body) if SIZE_INCLUDES_HEADER else len(body)
        hdr = struct.pack(self.e + "HHHHHLL", rc, size, 0, 0, 0, 0, 0)
        return hdr + body

    @staticmethod
    def pad(s, n):
        """null padded fixed width string, like GET_NAME / GET_VERSION return"""
        return s[:n - 1].ljust(n, b"\x00")

    def query_interface(self, lserial):
        # a wrong logical_com1 lands outside this window, same as the real box
        idx = lserial - LOGICAL_COM1
        if idx < 0 or idx >= N_IFACE:
            print(f"  ++ logical serial {lserial} out of range, base is {LOGICAL_COM1}")
            return self.response(ERR_UNKNOWN_SERIAL_PORT)

        self.served[idx] += 1
        # enabled (LONG), baudrate (LONG), requests served (ULONG)
        body = struct.pack(self.e + "lLL", 1, BAUDS[idx], self.served[idx])
        # then "device name (variable), device name string (variable)". the spec
        # gives no layout for these two, so this is a guess: device path, then a
        # friendly label, both null terminated
        body += b"/dev/ttyUSB%d\x00" % idx
        body += b"mock COM%d\x00" % (idx + 1)
        return self.response(NO_ERR, body)

    def handle(self, pkt):
        if len(pkt) < HDR_LEN:
            print("  ++ short packet")
            return self.response(ERR_MALFORMED_PACKET)

        cmd, size, timeout, ctrl, lserial, lock, _rsv = \
            struct.unpack(self.e + "HHHHHLL", pkt[:HDR_LEN])
        body = pkt[HDR_LEN:]

        print(f"  cmd {cmd} ({CMD_NAMES.get(cmd, '?')})  size {size}  "
              f"timeout {timeout}  ctrl {ctrl}  lserial {lserial}  lock {lock}")

        # a byte swapped header usually shows up right here
        if cmd not in CMD_NAMES:
            print("  ++ unknown command, the client's byte order is probably wrong")
            return self.response(ERR_UNKNOWN_COMMAND)

        want = HDR_LEN + len(body) if SIZE_INCLUDES_HEADER else len(body)
        if size != want:
            print(f"  ++ size field {size}, expected {want} "
                  f"({'whole packet' if SIZE_INCLUDES_HEADER else 'data only'})")
            return self.response(ERR_MALFORMED_PACKET)

        if lock != 0:
            print(f"  ++ nonzero lock code {lock}, spec says it must be 0")

        if cmd == GET_VERSION:
            return self.response(NO_ERR, self.pad(VERSION, 48))

        if cmd == GET_NAME:
            return self.response(NO_ERR, self.pad(NAME, 32))

        if cmd == GET_INTERFACES:
            fmt = "L" if IFACE_WIDTH == 4 else "H"
            return self.response(NO_ERR, struct.pack(self.e + fmt, N_IFACE))

        if cmd == QUERY_INTERFACE:
            return self.query_interface(lserial)

        if cmd == SEND_PACKET:
            # TODO: phase 1b, pretend nothing is on the bus for now
            print("  ++ SEND_PACKET, no pump emulated yet")
            return self.response(ERR_SERIAL_READ_TIMEOUT)

        # lock / unlock, the probe refuses to build these so we should never see them
        print(f"  ++ {CMD_NAMES[cmd]} should never be sent by our client")
        return self.response(ERR_UNKNOWN_COMMAND)


def main():
    mock = Mock()

    print("mock NCS")
    print(f"  listening      {HOST}:{PORT}")
    print(f"  byte order     {'little' if LITTLE_ENDIAN else 'big'}")
    print(f"  size field     {'whole packet' if SIZE_INCLUDES_HEADER else 'data only'}")
    print(f"  logical_com1   {LOGICAL_COM1}")
    print(f"  iface width    {IFACE_WIDTH}")
    print(f"  close after    {CLOSE_AFTER_RESPONSE}")
    print()

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        srv.bind((HOST, PORT))
    except OSError as e:
        print(f"  ++ bind failed: {e}")
        return 1
    srv.listen(5)

    try:
        while True:
            conn, addr = srv.accept()
            with conn:
                conn.settimeout(10.0)
                try:
                    pkt = conn.recv(4096)
                except socket.timeout:
                    print(f"[{addr[0]}:{addr[1]}] connected, no data")
                    continue
                if not pkt:
                    continue

                print(f"[{addr[0]}:{addr[1]}]")
                hexdump("  -->", pkt)
                resp = mock.handle(pkt)
                hexdump("  <--", resp)
                conn.sendall(resp)

                # the spec says the connection is closed after the server
                # returns the response but doesn't say who closes it. with
                # CLOSE_AFTER_RESPONSE off, the client has to hit its own recv
                # timeout, worth testing since we don't know what the real box does
                if not CLOSE_AFTER_RESPONSE:
                    print("  (holding the connection open, client must time out)")
                    try:
                        conn.recv(1)
                    except socket.timeout:
                        pass
                print()
    except KeyboardInterrupt:
        print("\nbye")
    finally:
        srv.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())